# Official Eshi Market Dev Code

# Eshi Market
# Version 1.0.0
# Homepage: https://eshimarket.com
# Author: Aaron Ayalew <aaronayalew@gmail.com>
# Documentation: TODO:

name: eshi_market
description: Eshi Market App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  woosignal: ^1.2.1
  woosignal_stripe: ^0.0.6
  razorpay_flutter: ^1.2.2
  wp_json_api: ^2.0.0
  shared_preferences: ^0.5.12
  cached_network_image: ^2.3.3
  page_transition: ^1.1.7+2
  package_info: ^0.4.3
  url_launcher: ^5.7.5
  flutter_money_formatter: ^0.8.3
  platform_alert_dialog: ^1.0.0+2
  flutter_web_browser: ^0.12.0
  pull_to_refresh: ^1.6.2
  intl: ^0.16.1
  flutter_swiper: ^1.1.6
  edge_alert: ^0.0.1
  bubble_tab_indicator: ^0.1.4
  status_alert: ^0.1.2
  math_expressions: ^2.0.1
  hexcolor: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.8.1
  auto_size_text: ^2.1.0
  html: ^0.14.0+3
  flutter_staggered_grid_view: ^0.3.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_application_id: "^1.0.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/appicon.png"

dependency_overrides:
  intl:

flutter:

  uses-material-design: true

  assets:
    - assets/images/camion.gif
    - assets/images/credit_cards.png
    - assets/images/shipping_icon.png
    - assets/images/dark_powered_by_stripe.png
    - assets/images/cash_on_delivery.jpeg
    - assets/images/razorpay.png
    - lang/en.json


  fonts:
     - family: Overpass
       fonts:
         - asset: assets/fonts/Overpass/Overpass-Regular.ttf
